modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="laputa"
version="1.0.0"
displayName="Laputa"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Fred Brandibur, MCreator"

[[dependencies.laputa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




